# Lab01S01 — top 100 repos + métricas RQ01–RQ04
query TopRepos($first: Int!) {
  search(query: "stars:>1 sort:stars-desc", type: REPOSITORY, first: $first) {
    repositoryCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ... on Repository {
        nameWithOwner
        url
        stargazerCount
        createdAt
        updatedAt
        pushedAt
        pullRequests(states: MERGED) {
          totalCount
        }
        releases {
          totalCount
        }
      }
    }
  }
}
